webtalk_init -webtalk_dir C:/Users/irwin/Desktop/ece416_irwin_adam_mithil/Lab04_Asynchronous_Serial_Receiver/Lab04_Asynchronous_Serial_Receiver.sim/sim_1/behav/xsim/xsim.dir/uart_rcvr_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 18 17:32:11 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "58629132-9601-4a07-b0a7-8ee1b8dc42d5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "106ce465dd5b46daab3058860a8518b7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "59" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 543560798 -regid "" -xml C:/Users/irwin/Desktop/ece416_irwin_adam_mithil/Lab04_Asynchronous_Serial_Receiver/Lab04_Asynchronous_Serial_Receiver.sim/sim_1/behav/xsim/xsim.dir/uart_rcvr_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/irwin/Desktop/ece416_irwin_adam_mithil/Lab04_Asynchronous_Serial_Receiver/Lab04_Asynchronous_Serial_Receiver.sim/sim_1/behav/xsim/xsim.dir/uart_rcvr_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/irwin/Desktop/ece416_irwin_adam_mithil/Lab04_Asynchronous_Serial_Receiver/Lab04_Asynchronous_Serial_Receiver.sim/sim_1/behav/xsim/xsim.dir/uart_rcvr_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
